Models/ErrorViewModel.cs
namespace DistribuUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string? Description { get; set; }
    }
}

Controllers/HomeController.cs
using DistribuUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DistribuUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(string description = "Error en el servidor")
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, Description = description });
        }
    }
}

Controllers/ProductController.cs
using DTOLibrary.Dtos;
using DTOLibrary.Extension;
using DTOLibrary.Interfaces;
using DTOLibrary.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using ServicesREST_API.RESTService;

namespace DistribuUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository _productService;

        private ITypeProductRepository _typeProductRepository;

        public ProductController(IProductRepository productService, ITypeProductRepository typeProductRepository)
        {
            _productService = productService;
            _typeProductRepository = typeProductRepository;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                ViewBag.TittleMain = "Todos los productos";

                var typeProduct = await _typeProductRepository.GetTypeProduct();

                ViewBag.TypeProduct = typeProduct.ToList();

                var productResult = await _productService.GetProducts();

                return View(productResult.ToList());
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home", new { description = ex.Message } );
            }
        }

        public async Task<IActionResult> GetProductsByTypeProdId(int typeProductId)
        {
            var productResult = await _productService.GetProducts();

            if(typeProductId != 0)
            {
                productResult = productResult.Where(a => a.TypeProductId == typeProductId).ToList();
            }

            return PartialView("_Products", productResult);
        }

        public async Task<IActionResult> Product(int productId)
        {
            try
            {
                ViewBag.TittleMain = "Producto";

                ProductViewModel product = new ProductViewModel();

                if (productId != 0)
                {
                    ViewBag.ProductResult = "Editar producto";

                    var productResult = await _productService.GetProductWithRelationsSuppliersByProductId(productId);

                    if (productResult != null)
                    {
                        product = productResult;
                    }
                    else
                    {
                        return Redirect("Index");
                    }
                }
                else
                {
                    ViewBag.ProductResult = "Crear un nuevo producto";
                }

                var typeProducts = await _typeProductRepository.GetTypeProduct();

                ViewBag.TypesProduct = typeProducts;

                return View(product);
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home", new { description = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> ProductEditCreate(ProductViewModel product)
        {
            try
            {

                ProductDto productDto = new ProductDto();

                productDto = product.MapProperties(productDto);

                if (product.ProductId == 0)
                {
                    var result = await _productService.InsertProduct(productDto);

                    return RedirectToAction("Product", new { productId = result.ProductId });
                }
                else
                {
                    await _productService.UpdateProduct(productDto);

                    return NoContent();
                }
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home", new { description = ex.Message });
            }
        }

        [HttpGet]
        public async Task<IActionResult> DeleteProduct(int productId) 
        {
            try
            {
                await _productService.DeleteProduct(productId);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home", new { description = ex.Message });
            }
        }

        public async Task<IActionResult> GetSuppliersByProductView(int productId)
        {
            var productResult = await _productService.GetProductWithRelationsSuppliersByProductId(productId);

            return PartialView("_SuppliersByProduct", productResult);
        }
    }
}

Controllers/ProductSupplierController.cs
using DTOLibrary.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace DistribuUI.Controllers
{
    public class ProductSupplierController : Controller
    {
        private ISupplierRepository _supplierRepository;

        private IProductSupplierRepository _productSupplierRepository;

        public ProductSupplierController(ISupplierRepository supplierRepository, IProductSupplierRepository productSupplierRepository)
        {
            _supplierRepository = supplierRepository;
            _productSupplierRepository = productSupplierRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SupplierToProduct(int productId, int productSupplierId)
        {
            try
            {
                ViewBag.TittleSupplierToProduct = "Agregar un proveedor al producto";

                ProductSupplierDto productSupplierDto = new ProductSupplierDto();

                productSupplierDto.ProductId = productId;

                var suppliers = await _supplierRepository.GetSuppliers();

                if (productSupplierId != 0)
                {
                    ViewBag.TittleSupplierToProduct = "Editar detalles de producto/proveedor";

                    var productSupplierResult = await _productSupplierRepository.GetProductSupplierById(productSupplierId);

                    if (productSupplierResult != null)
                    {
                        productSupplierDto = productSupplierResult;

                        ViewBag.Suppliers = suppliers.Where(a => a.SupplierId == productSupplierDto.SupplierId).ToList();
                    }
                }
                else
                {
                    ViewBag.Suppliers = suppliers;
                }

                return View(productSupplierDto);
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home", new { description = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddSupplier(ProductSupplierDto productSupplier)
        {

            try
            {
                if(productSupplier.ProductSupplierId == 0) 
                {
                    await _productSupplierRepository.InsertProductSupplier(productSupplier);
                }
                else
                {
                    await _productSupplierRepository.UpdateProductSupplier(productSupplier);
                }

                return RedirectToAction("Product", "Product", new { productId = productSupplier.ProductId });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { description = ex.Message });
            }
        }

        [HttpGet]
        public async Task<IActionResult> DeleteProductSupplier(int productSupplierId)
        {
            try
            {
                await _productSupplierRepository.DeleteProductSupplier(productSupplierId);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { description = ex.Message });
            }

            return NoContent();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Product/Index.cshtml
@model List<ProductDto>
@{
    Layout = "_Layout";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Listado de productos</h3>

        <div class="card-tools">
            <div class="input-group input-group-sm">
                <select class="custom-select" id="typeProductoSelect" style="margin-right: 10px; margin-top: 5px">
                    <option value="0">Todos</option>
                    @if (ViewBag.TypeProduct != null && ViewBag.TypeProduct.Count > 0)
                    {
                        @foreach (var tipoProducto in ViewBag.TypeProduct)
                        {
                            <option value="@tipoProducto.TypeProductId">@tipoProducto.TypeProductDesc</option>
                        }
                    }
                </select>

                <a class="btn btn-warning float-right" style="margin-right: 5px;" onclick="UpdateProduct()">
                    <i class="fas fa-refresh"></i> Actualizar
                </a>
                <a type="button" class="btn btn-primary float-right" style="margin-right: 5px;" href="/Product/Product">
                    <i class="fas fa-plus"></i> Agregar nuevo producto
                </a>
            </div>
        </div>
        <!-- /.card-tools -->
    </div>

    <div class="card-body" id="table-productsenabled">
        @await Html.PartialAsync("_Products", Model)
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

<script>
    function UpdateProduct() {
        var selectedTypeProductId = $('#typeProductoSelect').val();
        GetProductsByTypeProduct(selectedTypeProductId);
    }

    function GetProductsByTypeProduct(typeProductId) {
        $.ajax({
            url: '@Url.Action("GetProductsByTypeProdId", "Product")' + '?typeProductId=' + typeProductId,
            type: 'GET',
            success: function (result) {
                $('#table-productsenabled').html(result);

            },
            error: function (xhr, status, error) {
                console.error(error);
            }
        });
    }
</script>

Views/Product/Product.cshtml
@using DTOLibrary.ViewModels;
@model ProductViewModel
@{
    Layout = "_Layout";
}

<div class="col-md-9 mx-auto">
    <div class="card card-secondary">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.ProductResult</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <form asp-action="ProductEditCreate" asp-controller="Product" method="post">
                <input type="hidden" asp-for="ProductId" />
                <input type="hidden" asp-for="IsActive" />
                <div class="modal-footer right-content-between">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a class="btn btn-default" asp-action="Index" asp-controller="Product">Cancelar</a>
                </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <!-- text input -->
                            <div class="form-group">
                                <label>Código</label>
                                <input type="text" id="productCode" name="productCode" class="form-control" placeholder="Enter ..." required asp-for="ProductCode">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Nombre</label>
                                <input type="text" class="form-control" id="productName" name="productName" placeholder="Enter ..." required asp-for="ProductName">
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-9">
                            <!-- select -->
                            <div class="form-group">
                                <label>Tipo de Producto</label>
                                <div class="input-group">
                                    <select class="custom-select" id="tipoProductoSelect" asp-for="TypeProductId">
                                        @foreach (var tipoProducto in ViewBag.TypesProduct)
                                        {
                                            <option value="@tipoProducto.TypeProductId">@tipoProducto.TypeProductDesc</option>
                                        }
                                    </select>
                                    <div class="input-group-append">
                                        <span class="input-group-text">Agregar otro tipo</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label>Costo</label>
                                <input type="text" class="form-control" placeholder="Enter ..." asp-for="UnitPrice">
                            </div>
                        </div>
                    </div>
            </form>
        </div>
        @if(Model.ProductId != 0)
        {
            <div class="card-body" id="table-suppliersproduct">
                @await Html.PartialAsync("_SuppliersByProduct", Model)
            </div>
        }
    </div>
</div>

<script>
    function GetSuppliersByProductView(productId) {
        $.ajax({
            url: '@Url.Action("GetSuppliersByProductView", "Product")' + '?productId=' + productId,
            type: 'GET',
            success: function (result) {
                $('#table-suppliersproduct').html(result);
            },
            error: function (xhr, status, error) {
                console.error(error);
            }
        });
    }
</script>

Views/ProductSupplier/SupplierToProduct.cshtml
@model ProductSupplierDto
@{
    Layout = null;
}

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">@ViewBag.TittleSupplierToProduct</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-action="AddSupplier" asp-controller="ProductSupplier" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" asp-for="ProductSupplierId" />
        <div class="card-body">
            <div class="form-group">
                <label>Seleccionar proveedor</label>
                <div class="input-group">
                    <select class="custom-select" id="tipoProductoSelect" asp-for="SupplierId">
                        @if (ViewBag.Suppliers != null && ViewBag.Suppliers.Count > 0)
                        {
                            foreach (var supplier in ViewBag.Suppliers)
                            {
                                <option value="@supplier.SupplierId">@supplier.SupplierName</option>
                            }
                        }
                        else
                        {
                            <option value="">No hay proveedores disponibles</option>
                        }
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Clave de producto</label>
                <input type="text" id="ProductSupplierCode" name="ProductSupplierCode" class="form-control" placeholder="Enter ..." required asp-for="ProductSupplierCode">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Precio al proveedor</label>
                <input type="text" id="ProductSupplierUnitPrice" name="ProductSupplierUnitPrice" class="form-control" placeholder="Enter ..." required asp-for="ProductSupplierUnitPrice">
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer right-content-between">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>
<!-- /.card -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Distribución</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-area="" asp-controller="Product" asp-action="Index" class="nav-link">Inicio</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contacto</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-area="" asp-controller="Product" asp-action="Index" class="brand-link">
                <img src="/img/DistributionLogo.png" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Distribución</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-header">Opciones</li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Product" asp-action="Index" class="nav-link">
                                <i class="nav-icon far fa-calendar"></i>
                                <p>
                                    Listado de productos
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Product" asp-action="Index" class="nav-link">
                                <i class="nav-icon far fa-address-book"></i>
                                <p>
                                    Listado de proveedores
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Product" asp-action="Index" class="nav-link">
                                <i class="nav-icon far fa-handshake"></i>
                                <p>
                                    Producto y proveedor
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>@(ViewBag.TittleMain != null ? ViewBag.TittleMain : "")</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">

                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">

                @RenderBody()

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 1.0.1
            </div>
            <strong>Diseñado por <a href="https://leonel-rivera.com">Leonel Rivera</a>.</strong> All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/boostrap/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/js/demo.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
</body>
</html>

Views/Shared/_Products.cshtml
@using DTOLibrary.Dtos;
@model IEnumerable<ProductDto>

<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th style="width: 50px;">Editar</th>
            <th>Nombre de Producto</th>
            <th>Clave</th>
            <th>Precio</th>
            <th style="width: 50px;">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null)
        {
            @foreach (var product in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Product" asp-controller="Product" asp-route-productId="@product.ProductId" class="btn btn-info btn-sm edit-button btn-block">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                    </td>
                    <td>@product.ProductName</td>
                    <td>@product.ProductCode</td>
                    <td style="text-align:right">@product.UnitPrice</td>
                    <td>
                        <a class="btn btn-danger btn-sm delete-button btn-block" data-product-id="@product.ProductId" onclick="confirmDelete(@product.ProductId)">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Editar</th>
            <th>Nombre de Producto</th>
            <th>Clave</th>
            <th>Precio</th>
            <th>Eliminar</th>
        </tr>
    </tfoot>
</table>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>

    function confirmDelete(productId) {
        if (confirm('¿Estás seguro de que deseas eliminar este producto?')) {
            window.location.href = '/Product/DeleteProduct?productId=' + productId;
        }
    }

    $(function () {

            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });
 
</script>